CREATE OR REPLACE PROCEDURE internal_error_funcs
IS
BEGIN
    RAISE NO_DATA_FOUND;
EXCEPTION
WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('SQLCODE = '||SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM = '||SQLERRM(SQLCODE));
    DBMS_OUTPUT.PUT_LINE('DBMS_UTILITY.FORMAT_ERROR_STACK = '||DBMS_UTILITY.FORMAT_ERROR_STACK);
    DBMS_OUTPUT.PUT_LINE('DBMS_UTILITY.FORMAT_ERROR_BACKTRACE = '||DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    DBMS_OUTPUT.PUT_LINE('DBMS_UTILITY.FORMAT_CALL_STACK = '||DBMS_UTILITY.FORMAT_CALL_STACK);
END;
/
EXEC internal_error_funcs;